import Head from "next/head";
import NewPost from "../../../components/NewPost";
import Post from "../../../components/Post";
import { Container, Paper } from "@mui/material";
import CssBaseline from "@mui/material/CssBaseline";
import wall3 from "../../../assets/wall3.jpg";
import SinglePost from "../../../components/SinglePost";

export default function Home({ post, host }) {
  console.log("serveeeeeeer", host);
  return (
    <div
      style={{
        backgroundImage: `url(${wall3.src})`,
        backgroundRepeat: "no-repeat",
        backgroundAttachment: "fixed",
        backgroundPosition: "center",
        backgroundSize: "auto",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CssBaseline />

      <Container
        style={{
          minHeight: "100vh",
          zIndex: 3,
          position: "relative",
          background: "inherit",
        }}
      >
        <Container
          style={{
            position: "absolute",
            filter: "blur(3px)",
            zIndex: -2,
            height: "100%",
            width: "100%",
            background: "inherit",
          }}
        ></Container>
        <SinglePost item={post} />
      </Container>
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const { req, query, response, asPath, pathname } = context;
  let host = null;
  let post = null;
  if (req) {
    host = req.headers.referer;
    const res = await fetch(`${host}api/posts/${context.params.id}`);
    const postOverall = await res.json();
    post = postOverall.content;
  }

  return {
    props: { post, host },
  };
};
